# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382450b3013cf4e1b18ab1a1ec027e10a6abb4bbe48a6ac37eb1c3da3e819ac66a34a86a12e2b78bc7b1aa2108a8fbb5c9218b08456d84d6f8c022201c98bc2a

test:
  secret_key_base: 0a307c6f73fab6e79a594bb7f6f8715b0b780180873671b8c8a75521518208ea37096ff5b831e5b3de9f52f7049d09c08a643e9af8a6fe980c60cf6e200f8195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
